[package]
name = "time_back"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
active-win-pos-rs = "0.8.3"
chrono = "0.4.34"
confy = "0.6.0"
device_query = "2.0.0"
eframe = "0.26.2"
egui_extras = "0.26.2"
egui_plot = "0.26.2"
humantime = "2.1.0"
png = "0.17.13"
serde = { version = "1.0.197", features = [ "derive" ] }
serde_json = "1.0.114"
tinyfiledialogs = "3.9.1"
